name: ReleaseAutomation

on:
  release:
    types: [published]

env:
  # Path to the solution file relative to the root of the project
  SOLUTION_FILE_PATH: "Coral.sln"

# Give permission to write to the release
permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build project
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /p:Configuration=Release /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}

    # Del or Remove-Item has a bug where if you try to exclude file types recursivly, the command breaks and deletes random files
    # So here we first gather all the files we want for deletion and then only delete those files
    - name: Delete unneeded files
      shell: pwsh
      run: |
        Get-ChildItem -Exclude *.asset, *.rename, *.hlsl, *hlsli -Path Assets\ -Recurse -File | Remove-Item
        Get-ChildItem -Exclude *.asset, *.rename, *.hlsl, *hlsli -Path Games\ExampleGame\Assets\ -Recurse -File | Remove-Item

    # Moving build files to the root folder, which makes sure .exe is in the first folder for the user and the assets are in the correct place
    - name: Move build files
      shell: pwsh
      run: Move-Item -Path Games/ExampleGame/Build/x64/Release/*

    - name: Run Unit Tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      timeout-minutes: 10
      run:  |
        $processInfo = New-Object System.Diagnostics.ProcessStartInfo
        $processInfo.FileName = "Lichgate.exe"
        $processInfo.Arguments = "run_tests"
        $processInfo.WorkingDirectory = $pwd
        $processInfo.RedirectStandardOutput = $true
        $processInfo.RedirectStandardError = $true
        $processInfo.UseShellExecute = $false
        
        $process = New-Object System.Diagnostics.Process
        $process.StartInfo = $processInfo
        
        $process.Start() | Out-Null
        
        $output = $process.StandardOutput.ReadToEnd() + $process.StandardError.ReadToEnd()
        $process.WaitForExit()
        
        echo "Executable Output:"
        echo $output
        
        echo "Exit Code: "
        echo $process.ExitCode
        exit $process.ExitCode

    - name: Zip build
      shell: pwsh
      # We zip all the assets with the exe and needed dll's
      run: 7z a -tzip Lichgate.zip Assets/ Games/ExampleGame/Assets/ Lichgate.exe *.dll

    - name: Upload build
      uses: AButler/upload-release-assets@v3.0
      with:
        files: "Lichgate.zip"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
