name: ReleaseAutomation

on:
  release:
    types: [published]

env:
  # Path to the solution file relative to the root of the project
  SOLUTION_FILE_PATH: "Coral.sln"

# Give permission to write to the release
permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build project
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /p:Configuration=Release /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}

    # Del or Remove-Item has a bug where if you try to exclude file types recursivly, the command breaks and deletes random files
    # So here we first gather all the files we want for deletion and then only delete those files
    - name: Delete unneeded files
      shell: pwsh
      run: |
        Get-ChildItem -Exclude *.asset, *.rename, *.hlsl, *hlsli -Path Assets\ -Recurse -File | Remove-Item
        Get-ChildItem -Exclude *.asset, *.rename, *.hlsl, *hlsli -Path Games\ExampleGame\Assets\ -Recurse -File | Remove-Item

    # Yes. Our project is for now named ExampleGame, if we will change it, this will break. We also copy the engine and game assets
    - name: Zip build
      shell: pwsh
      run: 7z a -tzip Lichgate.zip Games/ExampleGame/Build/x64/Release/ Assets/ Games/ExampleGame/Assets/

    - name: Upload build
      uses: AButler/upload-release-assets@v3.0
      with:
        files: "Lichgate.zip"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
