# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: WindowsBuildAndRun

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

  # Cancel in-progress runs when a new workflow with the same group name is triggered
  cancel-in-progress: true

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: "Coral.sln"

permissions:
  contents: read

jobs:
  build-and-run:
    runs-on: windows-latest
    strategy:
      fail-fast: false # We want to run all configurations to see if the problem is for all of them or not
      matrix:
        build-configuration: [Debug, EditorDebug, Release, EditorRelease]
    steps:
    - uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.build-configuration}} /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}} /INCREMENTAL:NO
      
    - name: Run Unit Tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      timeout-minutes: 1
      run:  |
        $output = & "Games\ExampleGame\Build\x64\${{matrix.build-configuration}}\ExampleGame.exe" run_tests 2>&1 -WorkingDirectory $pwd
                
        echo "Executable Output:"
        echo $output
        
        echo "Exit Code: "
        echo $LASTEXITCODE
        exit $LASTEXITCODE
