# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: WindowsBuild

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: "Engine.sln"

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: windows-latest
    strategy:
      fail-fast: false # We want to run all configurations to see if the problem is for all of them or not
      matrix:
        build-configuration: [Debug, EngineDebug, Release, EngineRelease]

    steps:
    - uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.build-configuration}} /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}

    - name: Run Unit Tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: Games\ExampleGame\Build\x64\${{matrix.build-configuration}}\ExampleGame.exe run_tests
